export const SELECTORS = {
  signupModal: "#signInModal",
  loginModal: "#logInModal",
  signupUsername: "#sign-username",
  signupPassword: "#sign-password",
  loginUsername: "#loginusername",
  loginPassword: "#loginpassword",
  userNameDisplay: "#nameofuser",
  cartLink: "#cartur",
  orderModal: "#orderModal",
  orderName: "#name",
  orderCountry: "#country",
  orderCity: "#city",
  orderCard: "#card",
  orderMonth: "#month",
  orderYear: "#year",
  totalPrice: "#totalp",
  navbar: ".navbar-nav",
  categoriesSection: "#cat",
  navBarHeader: "#nava",
  cardTitle: ".card-title",
};
